name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check fmt
      run: cargo fmt --all -- --check
    - name: Clippy
      run: cargo clippy --all --all-features -- --deny warnings
    - name: Build
      run: cargo build --verbose
    - name: Doc tests
      run: cargo test --doc
    - name: Run tests
      run: cargo test --verbose
